view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGenerationJob.java
Currently the FlinkFixedPartitioner uses a static mapping i.e. subtask_id % num_partitions and the subtask_id is dependent on the *parallelism* config specified.
This has 2 problems:
1. The parallelism is specified for the producer (upstream job) and can be different from the downstream job.
2. The number of partitions could be different across the upstream and downstream jobs
To avoid skew by not explicitly specifying a partitioner flink will fallback on Kafka producer's default partitioning strategy - which is round-robin.
=> Don't explicitly set a flink kafka partitioner  

view-creator-framework/build.gradle.kts, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/TableCreationTool.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/ViewCreatorLauncher.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotMultiTableCreationTool.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotTableCreationTool.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/ViewCreatorLauncherTest.java, view-creator-framework/src/test/resources/all-views.conf, view-creator-framework/src/test/resources/sample-view-generation-spec.conf
As a platform service, view creator job can override configuration through Helm chart values.
=> refactor view creator job as a platform service

.snyk, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
use platform-service-framework  to 0.1.8 and flink-utils to 0.1.6
=> use platform-service-framework and flink-utils

view-creator-framework/build.gradle.kts, view-creator-framework/src/test/resources/all-views.conf, view-creator-framework/src/test/resources/sample-view-generation-spec.conf, view-generator-framework/build.gradle.kts
=> update plat service

view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/ViewCreatorLauncher.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/MultiViewGeneratorLauncher.java
remove redundant override,not needed in latest version, causing NPE
now same is already done as part of framework: https://github.com/hypertrace/service-framework/blob/master/platform-service-framework/src/main/java/org/hypertrace/core/serviceframework/PlatformService.java#L55
=> remove redundant override,not needed in latest version, causing NPE

view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGeneratorLauncher.java
=> remove get service name

.github/CODEOWNERS
- updating code-owners from individual to team
=> updating code owners as team

.snyk, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
This helps to fix Snyk failures.
=> Upgrading the libraries to latest versions.

.circleci/config.yml, build.gradle.kts, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
Also update some of the old dependencies
=> chore: fix snyk issue

.snyk, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
Pull in https://github.com/hypertrace/service-framework/pull/25
=> chore: update vulnerable dependencies

view-creator-framework/build.gradle.kts
Fixes https://github.com/hypertrace/hypertrace-ingester/runs/2039531831
=> chore: Fix vulnerabilities

.snyk, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
Update dependencies to clean up outstanding snyk vulnerabilities.
=> chore: update dependencies to fix vulns

build.gradle.kts, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/ViewCreationSpec.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/Pair.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotMultiTableCreationTool.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotUtils.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/ViewCreationSpecTest.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/ViewCreatorLauncherTest.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/pinot/PinotUtilsTest.java, view-generator-framework/build.gradle.kts, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/JavaCodeBasedViewGenerator.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/ViewGenerator.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/InputToViewMapper.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/MultiViewGeneratorLauncher.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGenerationProcessTransformer.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGeneratorLauncher.java, view-generator-framework/src/test/java/org/hypertrace/core/viewgenerator/JavaCodeBasedViewGeneratorTest.java, view-generator-framework/src/test/java/org/hypertrace/core/viewgenerator/TestViewGenerator.java
- adds spotless code style plugin
=> chore: adding spotless code style plugin

view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotTableSpec.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotUtils.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotViewCreatorConfig.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/pinot/PinotUtilsTest.java, view-creator-framework/src/test/resources/sample-view-generation-spec.conf, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/MultiViewGeneratorLauncher.java
Added support for configuring tag override configuration and tier configs.
Added unit tests. 
None
=> feat: support for tier and tag override configurations

view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
Upgraded couple versions to fix vulnerabilities
=> Upgraded netty and hypertrace service-framework versions

view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
=> fix: update vulnerable deps

view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGenerationProcessTransformer.java
=> bugfix: config parsing fix

view-generator-framework/build.gradle.kts, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGenerationProcessTransformer.java, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGeneratorLauncher.java, view-generator-framework/src/test/java/org/hypertrace/core/viewgenerator/ViewGeneratorLauncherTest.java, view-generator-framework/src/test/resources/configs/test-view-generator/application.conf
Fix the topology
Unit testing using kafka streams test framework
NA
=> bugfix: Fix topology and add unit test

view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotTableSpec.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotUtils.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/ViewCreationSpecTest.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/pinot/PinotUtilsTest.java, view-creator-framework/src/test/resources/sample-view-generation-spec.conf
Please include a summary of the change, motivation and context.
Added unit tests
NA
=> support configuring replicas per partition

build.gradle.kts, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts, view-generator-framework/src/main/java/org/hypertrace/core/viewgenerator/service/ViewGeneratorLauncher.java
Please include a summary of the change, motivation and context.
Local testing & unit testing
NA
=> custom avro field paritioner

view-creator-framework/build.gradle.kts, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotTableSpec.java, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotUtils.java, view-creator-framework/src/test/avro/TestView.avdl, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/ViewCreationSpecTest.java, view-creator-framework/src/test/java/org/hypertrace/core/viewcreator/pinot/PinotUtilsTest.java, view-creator-framework/src/test/resources/sample-view-generation-spec.conf
Support advanced table config (startree config, segment partition config, routing config)
Added unit tests. 
NA
=> support for advanced pinot table config

view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
Kafka upgrade and TPL upgrade.
Unit testing and manual testing on sandbox environment. 
NA.
=> kafka upgrade

view-creator-framework/build.gradle.kts, view-creator-framework/src/main/java/org/hypertrace/core/viewcreator/pinot/PinotUtils.java, view-generator-framework/build.gradle.kts
- Upgraded pinot-tools to 0.10.0 as we are on pinot 10 (https://github.com/hypertrace/pinot/blob/main/Dockerfile#L3)
- Other libs to fix high severity
=> fix: upgrades libs for fixing vulnerabilities

owasp-suppressions.xml, view-creator-framework/build.gradle.kts, view-generator-framework/build.gradle.kts
Update a few dependencies, clean up suppressions
=> chore: update dependencies and suppressions
